---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# togglvis

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the released version of togglvis from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("remotes")
remotes::install_github("karissawhiting/togglvis")
```

## Example

This is a basic example showing how to get data from the togglr API and process
and visualize it.

```{r example}
library(togglvis)
library(dplyr)
## basic example code
```

```{r, echo=FALSE}
load(here::here("data-raw", "report.RData"))
```

Get summary report data using togglr app, or download data from web browser

```{r, eval = FALSE}
# See togglr documentation for how to set up the API key
report <- togglr::get_detailled_report()

```

```{r cars}
processed_report <- process_report(report)
time_bar_chart(processed_report)

```

